# Generated by Django 4.2.1 on 2023-05-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dirname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='pon el nombre del director', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePelicula', models.CharField(max_length=64)),
                ('sumary', models.TextField(help_text='Resumen pelicula', max_length=100)),
                ('Dirname', models.ManyToManyField(to='catalog.dirname')),
            ],
        ),
    ]
